name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / hadolint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./
        with:
          reporter: github-check
          level: info
          exclude: Dockerfile.dockerignore

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / hadolint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          exclude: Dockerfile.dockerignore
