name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / hadolint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./
        with:
          reporter: github-check
          level: info
          exclude: Dockerfile.dockerignore

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / hadolint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          exclude: Dockerfile.dockerignore
