---
name: yamllint
on: [pull_request]

jobs:
  yamllint:
    name: check / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: yamllint
        uses: reviewdog/action-yamllint@1dca3ad811867be18fbe293a9818d715a6c2cd46 # v1.20.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'
